# Generated by Django 4.2.23 on 2025-07-30 14:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='Название категории')),
                ('code', models.SlugField(unique=True, verbose_name='Идентификатор категории')),
            ],
            options={
                'verbose_name': 'категория',
                'verbose_name_plural': 'Категории',
            },
        ),
        migrations.CreateModel(
            name='OperationStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, unique=True, verbose_name='Название статуса операции')),
                ('code', models.SlugField(unique=True, verbose_name='Идентификатор статуса операции')),
            ],
            options={
                'verbose_name': 'статус операции',
                'verbose_name_plural': 'Статусы операции',
            },
        ),
        migrations.CreateModel(
            name='OperationType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, unique=True, verbose_name='Название типа операции')),
                ('code', models.SlugField(unique=True, verbose_name='Идентификатор типа операции')),
            ],
            options={
                'verbose_name': 'тип операции',
                'verbose_name_plural': 'Типы операции',
            },
        ),
        migrations.CreateModel(
            name='SubCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='Название подкатегории')),
                ('code', models.SlugField(unique=True, verbose_name='Идентификатор подкатегории')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subcategories', to='money.category', to_field='code', verbose_name='Категория')),
            ],
            options={
                'verbose_name': 'подкатегория',
                'verbose_name_plural': 'Подкатегории',
            },
        ),
        migrations.CreateModel(
            name='Record',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания записи')),
                ('operation_date', models.DateField(verbose_name='Дата совершения операции')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Сумма')),
                ('comment', models.TextField(blank=True, null=True, verbose_name='Комментарий')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='records_by_category', to='money.category', to_field='code', verbose_name='Категория')),
                ('operation_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='records_by_type', to='money.operationtype', to_field='code', verbose_name='Тип операции')),
                ('status', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='records_by_status', to='money.operationstatus', to_field='code', verbose_name='Статус операции')),
                ('subcategory', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='records_by_subcategory', to='money.subcategory', to_field='code', verbose_name='Подкатегория')),
            ],
            options={
                'verbose_name': 'запись',
                'verbose_name_plural': 'Записи',
                'ordering': ('-operation_date',),
            },
        ),
        migrations.AddField(
            model_name='category',
            name='operation_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='categories', to='money.operationtype', to_field='code', verbose_name='Тип операции'),
        ),
        migrations.AddConstraint(
            model_name='subcategory',
            constraint=models.UniqueConstraint(fields=('name', 'category'), name='unique_category_name'),
        ),
        migrations.AddConstraint(
            model_name='category',
            constraint=models.UniqueConstraint(fields=('name', 'operation_type'), name='unique_type_name'),
        ),
    ]
