# Generated by Django 4.2.23 on 2025-07-31 14:39

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('money', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='record',
            name='operation_date',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='Дата совершения операции'),
        ),
    ]
